include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  language:
    strict-casts: false
  errors:
    prefer_const_constructors: warning
    avoid_print: warning
    non_constant_identifier_names: warning

linter:
  rules:
    public_member_api_docs: false
    always_use_package_imports: false
    prefer_relative_imports: true
    lines_longer_than_80_chars: false
    avoid_redundant_argument_values: false
    sort_constructors_first: false
    always_put_required_named_parameters_first: false
    prefer_final_in_for_each: false
    omit_local_variable_types: false
