name: lesson_challenge
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  copy_with_extension: ^5.0.4
  dio: ^5.3.2
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^14.1.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  provider: ^6.0.5

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  test: ^1.24.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

